import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import GlobalProvider from "@/context/GlobaContext";
import { ThemeButton } from "@/components/ThemeButton";
export const metadata: Metadata = {
  title: "Tasks Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark:bg-[#181818] bg-slate-300 !text-black">
        <body className={inter.className}>
          <GlobalProvider>
            <SideBar />
            <main className="w-full h-full overflow-hidden rounded-2xl dark:bg-gray-800 bg-slate-200 p-6">
              <div className="dark:bg-slate-900 bg-neutral-300 rounded-2xl p-4 flex justify-between items-center ">
                <h1 className="md:text-2xl font-bold text-gray-700 dark:text-gray-500">
                  Tasks Manager
                </h1>
                <ThemeButton />
              </div>
              {children}
            </main>
          </GlobalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
